// Signup screen types
export const SIGNUP_SCREEN_AVATAR_UPDATE = 'SIGNUP_SCREEN_AVATAR_UPDATE';
export const SIGNUP_SCREEN_USERNAME_UPDATE = 'SIGNUP_SCREEN_USERNAME_UPDATE';
export const SIGNUP_SCREEN_ERROR_UPDATE = 'SIGNUP_SCREEN_ERROR_UPDATE';
export const SIGNUP_SCREEN_STATUS_UPDATE = 'SIGNUP_SCREEN_STATUS_UPDATE';