// Signup screen types
export const SIGNUP_SCREEN_AVATAR_UPDATE = 'SIGNUP_SCREEN_AVATAR_UPDATE';
export const SIGNUP_SCREEN_USERNAME_UPDATE = 'SIGNUP_SCREEN_USERNAME_UPDATE';
export const SIGNUP_SCREEN_ERROR_UPDATE = 'SIGNUP_SCREEN_ERROR_UPDATE';
export const SIGNUP_SCREEN_STATUS_UPDATE = 'SIGNUP_SCREEN_STATUS_UPDATE';

// Splash screen types
export const SPLASH_SCREEN_GET_USER_INFO = 'SPLASH_SCREEN_GET_USER_INFO';
export const SPLASH_SCREEN_ERROR_UPDATE = 'SPLASH_SCREEN_ERROR_UPDATE';

// Home screen types
export const HOME_SCREEN_CONNECT_SOCKETS = 'HOME_SCREEN_CONNECT_SOCKETS';
export const HOME_SCREEN_ERROR_UPDATE = 'HOME_SCREEN_ERROR_UPDATE';